services:
  mysql:
    image: mysql:8
    container_name: mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql  # Local directory for MySQL data
    restart: always

  espocrm:
    image: espocrm/espocrm
    container_name: espocrm
    env_file: .env
    environment:
      ESPOCRM_DATABASE_PLATFORM: ${ESPOCRM_DATABASE_PLATFORM}
      ESPOCRM_DATABASE_HOST: ${ESPOCRM_DATABASE_HOST}
      ESPOCRM_DATABASE_USER: ${ESPOCRM_DATABASE_USER}
      ESPOCRM_DATABASE_PASSWORD: ${ESPOCRM_DATABASE_PASSWORD}
      ESPOCRM_ADMIN_USERNAME: ${ESPOCRM_ADMIN_USERNAME}
      ESPOCRM_ADMIN_PASSWORD: ${ESPOCRM_ADMIN_PASSWORD}
      ESPOCRM_SITE_URL: ${ESPOCRM_SITE_URL}
    volumes:
      - ./espocrm:/var/www/html  # Local directory for EspoCRM data
    restart: always
    ports:
      - 8086:80  # Change host port to 8086
    depends_on:
      - mysql

  espocrm-daemon:
    image: espocrm/espocrm
    container_name: espocrm-daemon
    env_file: .env
    volumes:
      - ./espocrm:/var/www/html  # Local directory for EspoCRM data
    restart: always
    entrypoint: docker-daemon.sh
    depends_on:
      - espocrm
      - mysql

  espocrm-websocket:
    image: espocrm/espocrm
    container_name: espocrm-websocket
    env_file: .env
    environment:
      ESPOCRM_CONFIG_USE_WEB_SOCKET: ${ESPOCRM_CONFIG_USE_WEB_SOCKET}
      ESPOCRM_CONFIG_WEB_SOCKET_URL: ${ESPOCRM_CONFIG_WEB_SOCKET_URL}
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBSCRIBER_DSN: ${ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBSCRIBER_DSN}
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBMISSION_DSN: ${ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBMISSION_DSN}
    volumes:
      - ./espocrm:/var/www/html  # Local directory for EspoCRM data
    restart: always
    entrypoint: docker-websocket.sh
    ports:
      - 8081:8086
    depends_on:
      - espocrm
      - mysql

# Use bind mounts for local storage
volumes:
  mysql:
    driver: local
  espocrm:
    driver: local