version: '3'

services:
  espocrm:
    image: espocrm/espocrm
    container_name: espocrm
    ports:
      - "8080:80"  # Map port 8080 on your machine to port 80 in the container
    volumes:
      - ./data:/var/www/html  # Optional: To persist data
    environment:
      - ESPOCRM_DATABASE_HOST=db
      - ESPOCRM_DATABASE_PORT=3306
      - ESPOCRM_DATABASE_NAME=espocrm
      - ESPOCRM_DATABASE_USER=espocrm
      - ESPOCRM_DATABASE_PASSWORD=espocrm
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: espocrm_db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=espocrm
      - MYSQL_USER=espocrm
      - MYSQL_PASSWORD=espocrm
    volumes:
      - ./db:/var/lib/mysql