version: '3'

networks:
  internal:
    driver: bridge

services:
  mysql:
    image: mysql:8
    container_name: mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql:delegated
    restart: always
    networks:
      - internal
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  espocrm:
    image: espocrm/espocrm
    container_name: espocrm
    env_file: .env
    environment:
      ESPOCRM_DATABASE_PLATFORM: ${ESPOCRM_DATABASE_PLATFORM}
      ESPOCRM_DATABASE_HOST: mysql
      ESPOCRM_DATABASE_USER: ${MYSQL_USER}
      ESPOCRM_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      ESPOCRM_ADMIN_USERNAME: ${ESPOCRM_ADMIN_USERNAME}
      ESPOCRM_ADMIN_PASSWORD: ${ESPOCRM_ADMIN_PASSWORD}
      ESPOCRM_SITE_URL: ${ESPOCRM_SITE_URL}
    volumes:
      - ./espocrm:/var/www/html:delegated
    restart: always
    ports:
      - 8086:80
    networks:
      - internal
    depends_on:
      mysql:
        condition: service_healthy

  espocrm-daemon:
    image: espocrm/espocrm
    container_name: espocrm-daemon
    env_file: .env
    volumes:
      - ./espocrm:/var/www/html:delegated
    restart: always
    entrypoint: docker-daemon.sh
    networks:
      - internal
    depends_on:
      - espocrm
      - mysql

  espocrm-websocket:
    image: espocrm/espocrm
    container_name: espocrm-websocket
    env_file: .env
    environment:
      ESPOCRM_CONFIG_USE_WEB_SOCKET: ${ESPOCRM_CONFIG_USE_WEB_SOCKET}
      ESPOCRM_CONFIG_WEB_SOCKET_URL: ${ESPOCRM_CONFIG_WEB_SOCKET_URL}
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBSCRIBER_DSN: ${ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBSCRIBER_DSN}
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBMISSION_DSN: ${ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBMISSION_DSN}
    volumes:
      - ./espocrm:/var/www/html:delegated
    restart: always
    entrypoint: docker-websocket.sh
    networks:
      - internal
    ports:
      - 8081:8086
    depends_on:
      - espocrm
      - mysql

volumes:
  mysql:
    driver: local
  espocrm:
    driver: local