services:
  espocrm:
    image: espocrm/espocrm
    container_name: espocrm
    ports:
      - "8080:80"  # Map port 8080 on your machine to port 80 in the container
    volumes:
      - ./data:/var/www/html  # Optional: To persist data
    environment:
      - ESPOCRM_DATABASE_HOST=${ESPOCRM_DATABASE_HOST}
      - ESPOCRM_DATABASE_PORT=${ESPOCRM_DATABASE_PORT}
      - ESPOCRM_DATABASE_NAME=${ESPOCRM_DATABASE_NAME}
      - ESPOCRM_DATABASE_USER=${ESPOCRM_DATABASE_USER}
      - ESPOCRM_DATABASE_PASSWORD=${ESPOCRM_DATABASE_PASSWORD}
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: espocrm_db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql